import { EmailRecord, MetricCardData } from "./email-tracker-types";

export const EMAIL_METRICS_DATA: MetricCardData[] = [
  {
    title: "Total Professors",
    count: 126,
    subtitle: "All tracked professors",
    borderColor: "border-[#6366F1]",
    iconBg: "bg-[#EEF2FF]",
    iconColor: "text-[#4F46E5]",
    type: "professors",
  },
  {
    title: "Emails Sent",
    count: 89,
    subtitle: "This month",
    borderColor: "border-[#3B82F6]",
    iconBg: "bg-[#EFF6FF]",
    iconColor: "text-[#3B82F6]",
    type: "sent",
  },
  {
    title: "Replies Received",
    count: 34,
    subtitle: "Positive: 18\nNegative: 5",
    borderColor: "border-[#22C55E]",
    iconBg: "bg-[#F0FDF4]",
    iconColor: "text-[#22C55E]",
    type: "replies",
  },
  {
    title: "Pending Reminders",
    count: 12,
    subtitle: "Due in next 7 days",
    borderColor: "border-[#F97316]",
    iconBg: "bg-[#FFF7ED]",
    iconColor: "text-[#F97316]",
    type: "reminders",
  },
  {
    title: "Interview Scheduled",
    count: 7,
    subtitle: "This month",
    borderColor: "border-[#EAB308]",
    iconBg: "bg-[#FEFCE8]",
    iconColor: "text-[#EAB308]",
    type: "interviews",
  },
  {
    title: "Applications",
    count: 23,
    subtitle: "Submitted",
    borderColor: "border-[#A855F7]",
    iconBg: "bg-[#FAF5FF]",
    iconColor: "text-[#A855F7]",
    type: "applications",
  },
];

export const INITIAL_EMAIL_RECORDS: EmailRecord[] = [
  {
    id: "email-1",
    professorName: "John Smith",
    professorTitle: "Professor of CS",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=240&q=80",
    universityName: "Stanford",
    universitySub: "University",
    universityLogoType: "stanford",
    email: "john.smith@stanford.edu",
    sentDate: "May 10, 2024",
    sentTime: "10:30 AM",
    reminderDate: "May 17, 2024",
    reminderTime: "10:30 AM",
    replyDate: "May 18, 2024",
    replyTime: "02:15 PM",
    status: "Positive Reply",
    notes:
      "Prof. Smith showed interest in my research background. Scheduled a Zoom meeting for next week.",
    subject: "PhD Opportunity - Fall 2025",
    location: "Stanford, CA, USA",
    website: "https://cs.stanford.edu/~jsmith",
    interviewDate: "May 25, 2024",
    interviewTime: "11:00 AM",
    attachments: [
      { name: "MY_CV.pdf", size: "2.4 MB", type: "pdf" },
      { name: "Research_Proposal.pdf", size: "1.8 MB", type: "pdf" },
    ],
    lastUpdated: {
      date: "May 18, 2024 at 02:20 PM",
      author: "Sahriar Wahid",
    },
  },
  {
    id: "email-2",
    professorName: "David Lee",
    professorTitle: "Assoc. Professor",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80",
    universityName: "Massachusetts",
    universitySub: "Institute of Tech.",
    universityLogoType: "mit",
    email: "david.lee@mit.edu",
    sentDate: "May 12, 2024",
    sentTime: "11:45 AM",
    reminderDate: "May 19, 2024",
    reminderTime: "11:45 AM",
    replyDate: "May 19, 2024",
    replyTime: "04:20 PM",
    status: "Interview",
    notes: "Invited for 45 min technical discussion on vision transformers.",
    subject: "Graduate Research Assistantship Inquiry",
    location: "Cambridge, MA, USA",
    website: "https://eecs.mit.edu/~davidlee",
    interviewDate: "May 28, 2024",
    interviewTime: "03:00 PM",
    attachments: [{ name: "CV_David_App.pdf", size: "2.1 MB", type: "pdf" }],
    lastUpdated: {
      date: "May 19, 2024 at 04:30 PM",
      author: "Sahriar Wahid",
    },
  },
  {
    id: "email-3",
    professorName: "Emma Brown",
    professorTitle: "Professor of DS",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=160&q=80",
    universityName: "University of",
    universitySub: "Toronto",
    universityLogoType: "toronto",
    email: "emma.brown@utoronto.ca",
    sentDate: "May 14, 2024",
    sentTime: "09:20 AM",
    reminderDate: "May 21, 2024",
    reminderTime: "09:20 AM",
    status: "No Response",
    notes: "Sent introductory email with portfolio and thesis summary.",
    subject: "PhD Supervision Inquiry - Machine Learning",
    location: "Toronto, Canada",
    website: "https://web.cs.toronto.edu/~ebrown",
    attachments: [{ name: "Thesis_Abstract.pdf", size: "1.2 MB", type: "pdf" }],
    lastUpdated: {
      date: "May 14, 2024 at 09:25 AM",
      author: "Sahriar Wahid",
    },
  },
  {
    id: "email-4",
    professorName: "Michael Chen",
    professorTitle: "Assistant Prof.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=160&q=80",
    universityName: "UC",
    universitySub: "Berkeley",
    universityLogoType: "berkeley",
    email: "mchen@berkeley.edu",
    sentDate: "May 15, 2024",
    sentTime: "01:10 PM",
    reminderDate: "May 22, 2024",
    reminderTime: "01:10 PM",
    reminderOverdue: true,
    status: "Reminder Due",
    notes: "First reminder due today. Need to follow up with updated preprint.",
    subject: "Inquiry on BAIR Lab Opportunities",
    location: "Berkeley, CA, USA",
    website: "https://people.eecs.berkeley.edu/~mchen",
    attachments: [{ name: "CV_Michael_Chen.pdf", size: "2.3 MB", type: "pdf" }],
    lastUpdated: {
      date: "May 15, 2024 at 01:15 PM",
      author: "Sahriar Wahid",
    },
  },
  {
    id: "email-5",
    professorName: "Sarah Johnson",
    professorTitle: "Lecturer",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=160&q=80",
    universityName: "ETH",
    universitySub: "Zurich",
    universityLogoType: "eth",
    email: "sarah.j@ethz.ch",
    sentDate: "May 16, 2024",
    sentTime: "03:30 PM",
    reminderDate: "May 23, 2024",
    reminderTime: "03:30 PM",
    status: "Not Sent",
    notes: "Drafted email awaiting final recommendation letter check.",
    subject: "Prospective Doctoral Research in Robotics",
    location: "Zurich, Switzerland",
    website: "https://ethz.ch/person/sjohnson",
    attachments: [{ name: "Research_Proposal.pdf", size: "2.0 MB", type: "pdf" }],
    lastUpdated: {
      date: "May 16, 2024 at 03:35 PM",
      author: "Sahriar Wahid",
    },
  },
];
