import { ApplicationItem, ApplicationMetric } from "./application-types";

export const APPLICATION_METRICS_DATA: ApplicationMetric[] = [
  { title: "Not Started", count: 3, percentage: "8%", type: "Not Started" },
  { title: "Preparing", count: 4, percentage: "11%", type: "Preparing" },
  { title: "Submitted", count: 6, percentage: "16%", type: "Submitted" },
  { title: "Interview", count: 2, percentage: "5%", type: "Interview" },
  { title: "Waiting", count: 3, percentage: "8%", type: "Waiting" },
  { title: "Accepted", count: 2, percentage: "5%", type: "Accepted" },
  { title: "Rejected", count: 1, percentage: "3%", type: "Rejected" },
  { title: "Visa", count: 1, percentage: "3%", type: "Visa" },
];

export const INITIAL_APPLICATIONS_DATA: ApplicationItem[] = [
  // Not Started (3)
  {
    id: "app-harvard",
    universityName: "Harvard University",
    program: "PhD in Computer Science",
    department: "School of Engineering and Applied Sciences",
    intake: "Fall 2025",
    deadline: "Dec 15, 2024",
    country: "USA",
    status: "Not Started",
    applicationId: "HAR-F25-CS-2041",
    progressPercent: 0,
    checklist: [
      { task: "Create Account", status: "Pending" },
      { task: "Personal Information", status: "Pending" },
      { task: "Academic History", status: "Pending" },
      { task: "Statement of Purpose", status: "Pending" },
    ],
  },
  {
    id: "app-oxford",
    universityName: "University of Oxford",
    program: "PhD in AI",
    department: "Department of Computer Science",
    intake: "Fall 2025",
    deadline: "Jan 10, 2025",
    country: "UK",
    status: "Not Started",
    applicationId: "OXF-F25-AI-8192",
    progressPercent: 0,
  },
  {
    id: "app-eth",
    universityName: "ETH Zurich",
    program: "PhD in Robotics",
    department: "Department of Information Technology and Electrical Engineering",
    intake: "Fall 2025",
    deadline: "Dec 1, 2024",
    country: "Switzerland",
    status: "Not Started",
    applicationId: "ETH-F25-ROB-5532",
    progressPercent: 0,
  },

  // Preparing (4)
  {
    id: "app-mit",
    universityName: "MIT",
    program: "PhD in EECS",
    department: "Electrical Engineering & Computer Science",
    applicationId: "MIT-F25-EECS-1024",
    intake: "Fall 2025",
    deadline: "Dec 15, 2024",
    country: "USA",
    status: "Preparing",
    isActiveFocus: true,
    progressPercent: 60,
    checklist: [
      { task: "Create Account", status: "Completed", date: "Nov 15, 2024" },
      { task: "Personal Information", status: "Completed", date: "Nov 15, 2024" },
      { task: "Academic History", status: "Completed", date: "Nov 16, 2024" },
      { task: "Test Scores", status: "Completed", date: "Nov 16, 2024" },
      { task: "Statement of Purpose", status: "Completed", date: "Nov 20, 2024" },
      { task: "LOR 1", status: "Completed", date: "Nov 18, 2024" },
      { task: "LOR 2", status: "Pending" },
      { task: "CV/Resume", status: "Pending" },
      { task: "Review & Submit", status: "Pending" },
    ],
  },
  {
    id: "app-stanford",
    universityName: "Stanford University",
    program: "PhD in CS",
    department: "Computer Science Department",
    applicationId: "STAN-F25-CS-4412",
    intake: "Fall 2025",
    deadline: "Dec 5, 2024",
    country: "USA",
    status: "Preparing",
    progressPercent: 40,
  },
  {
    id: "app-cmu",
    universityName: "Carnegie Mellon",
    program: "PhD in CS",
    department: "School of Computer Science",
    applicationId: "CMU-F25-CS-3391",
    intake: "Fall 2025",
    deadline: "Jan 5, 2025",
    country: "USA",
    status: "Preparing",
    progressPercent: 30,
  },
  {
    id: "app-berkeley",
    universityName: "UC Berkeley",
    program: "PhD in CS",
    department: "EECS Department",
    applicationId: "UCB-F25-CS-1109",
    intake: "Fall 2025",
    deadline: "Dec 10, 2024",
    country: "USA",
    status: "Preparing",
    progressPercent: 50,
  },

  // Submitted (6)
  {
    id: "app-toronto",
    universityName: "University of Toronto",
    program: "PhD in CS",
    department: "Department of Computer Science",
    submittedDate: "Nov 18, 2024",
    intake: "Fall 2025",
    country: "Canada",
    status: "Submitted",
    applicationId: "UOT-F25-CS-7718",
    progressPercent: 100,
  },
  {
    id: "app-imperial",
    universityName: "Imperial College London",
    program: "PhD in AI",
    department: "Department of Computing",
    submittedDate: "Nov 20, 2024",
    intake: "Fall 2025",
    country: "UK",
    status: "Submitted",
    applicationId: "ICL-F25-AI-9943",
    progressPercent: 100,
  },
  {
    id: "app-nus",
    universityName: "NUS Singapore",
    program: "PhD in Data Science",
    department: "School of Computing",
    submittedDate: "Nov 25, 2024",
    intake: "Fall 2025",
    country: "Singapore",
    status: "Submitted",
    applicationId: "NUS-F25-DS-6621",
    progressPercent: 100,
  },

  // Interview (2)
  {
    id: "app-gatech",
    universityName: "Georgia Tech",
    program: "PhD in CS",
    department: "College of Computing",
    interviewDate: "Jan 10, 2025",
    intake: "Fall 2025",
    country: "USA",
    status: "Interview",
    applicationId: "GT-F25-CS-5102",
    progressPercent: 80,
  },
  {
    id: "app-tum",
    universityName: "TUM Munich",
    program: "PhD in Robotics",
    department: "Department of Informatics",
    interviewDate: "Jan 22, 2025",
    intake: "Fall 2025",
    country: "Germany",
    status: "Interview",
    applicationId: "TUM-F25-ROB-4091",
    progressPercent: 85,
  },
];
